--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/Spleef
branches:
- master
projects:
  Spleef:
    path: ""
    libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: thebigsmilexd/gameapi/gameapi
      version: ^4.1.1
...
